language: node_js

node_js:
  - "8"

cache: npm

services:
  - docker

before_install:
  - docker-compose pull

script:
  - docker-compose run build make test

before_deploy:
  - docker-compose run build
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
